### ISSUE TITLE
AMD based laptop with Pop OS

### ISSUE THREAD

**Issue by alperyilmaz** [pop-os/amd-ppt-bin#3]
Hi,
I'm not sure if this is the right place to ask this question. I was planning to purchase a laptop with Ryzen 5 CPU along with NVIDIA GTX 1650 graphics card (Lenovo Legion 5). 
I was wondering if Pop OS would have any issues regarding various power profiles such as "integrated graphics" or "compute graphics". 
I'm not sure about compatibility of AMD drivers with Linux. If there are problems I'm sure System76/Pop OS is the one working on it actively, that's why I wanted post a issue. Will Pop OS work fine with AMD based laptop (with Nvidia graphics card)?
It looks like Reddit users [confirm](https://www.reddit.com/r/pop_os/comments/gzrsdk/can_i_use_pop_os_on_the_laptop_with_ryzen_cpu_and/) it's working smooth but I still wanted to get insights from an Pop OS insider about possible issues..
And system76-power repo refers to AMD+NVIDIA works fine.. (_Originally posted by @crawfxrd in https://github.com/pop-os/system76-power/issue_comments/628816739_).. So, my question is answered I guess..

**Comment by jacobgkau** [comment]
Hello! This is not the right place to ask questions like this. This is a development bug tracker.

> I was planning to purchase a laptop with Ryzen 5 CPU along with NVIDIA GTX 1650 graphics card (Lenovo Legion 5). I was wondering if Pop OS would have any issues regarding various power profiles such as "integrated graphics" or "compute graphics".

We generally only test Pop!_OS on System76 hardware. I'd generally expect it to work on other systems (particularly if Ubuntu works.)

The graphics profiles you're referring to would be for our Intel/NVIDIA switchable-graphics systems; none of our systems have both AMD and NVIDIA graphics (the Serval WS is an AMD CPU and NVIDIA GPU, while the upcoming Pangolin will be AMD-only for the CPU and GPU.) I think this would have more to do with [system76-power](https://github.com/pop-os/system76-power) than amd-ppt-bin, since system76-power handles graphics profiles.

For future questions about Pop!_OS on non-System76 hardware, the best places to go are [Reddit](https://reddit.com/r/pop_os/) and [Mattermost](https://chat.pop-os.org). (Owners of System76 hardware can get technical assistance by contacting [support](https://support.system76.com/).)
